version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: apexflow-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: apexflow
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: apexflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: apexflow-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
  minio_data:
